name: feedback_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  google_fonts: ^6.2.1
  http: ^1.6.0
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_colorpicker: ^1.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/zeusIcon.png
